#ifndef PLUGINLOGIN_GLOBAL_H
#define PLUGINLOGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGINLOGIN_LIBRARY)
#  define PLUGINLOGIN_EXPORT Q_DECL_EXPORT
#else
#  define PLUGINLOGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINLOGIN_GLOBAL_H
